namespace PacketSniffer.Packets.Application.Dhcp
{
    public enum DhcpOptionsTag
    {
        Pad = 0,
        SubnetMask = 1,
        TimeOffset = 2,
        Router = 3,
        TimeServer = 4,
        NameServer = 5,
        DomainServer = 6,
        LogServer = 7,
        QuotesServer = 8,
        LprServer = 9,
        ImpressServer = 10,
        RlpServer = 11,
        Hostname = 12,
        BootFileSize = 13,
        MeritDumpFile = 14,
        DomainName = 15,
        SwapServer = 16,
        RootPath = 17,
        ExtensionFile = 18,
        ForwardOnOff = 19,
        SrcRteOnOff = 20,
        PolicyFilter = 21,
        MaxDgAssembly = 22,
        DefaultIpttl = 23,
        MtuTimeout = 24,
        MtuPlateau = 25,
        MtuInterface = 26,
        MtuSubnet = 27,
        BroadcastAddress = 28,
        MaskDiscovery = 29,
        MaskSupplier = 30,
        RouterDiscover = 30,
        RouterRequest = 32,
        StaticRoute = 33,
        Trailers = 34,
        ArpTimeout = 35,
        Ethernet = 36,
        DefaultTcpttl = 37,
        KeepaliveTime = 38,
        KeepaliveData = 39,
        NisDomain = 40,
    }
}